### ISSUE TITLE
Bug with notifications

### ISSUE THREAD

**Issue by kareyuku** [dlist-top/dlist-top#1]
**Describe the bug**
Clicking notifaction which contain review gonna add to url /bots/ and not gonna go to this review.

**To Reproduce**
1. So first someone have to review our bot or server
2. Open notifications and click on the notifaction

**Expected behavior**
Open site with our bot/server and view this review

**Screenshots**
![unknown](https://user-images.githubusercontent.com/68489269/126382988-933b82f8-23cf-4a2b-bc26-d5b0cac62634.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera

**Comment by piratehacker** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/dlist-top/dlist-top/issues/1](https://trello.com/c/HkZdKmaZ/265-https-githubcom-dlist-top-dlist-top-issues-1)

**Comment by jakub-lat** [comment]
Fixed in latest version
