### ISSUE TITLE
Bug with Wallet

### ISSUE THREAD

**Issue by kareyuku** [dlist-top/dlist-top#2]
**Describe the bug**
When trying to buy points im gonna get white site with error

**To Reproduce**
1. Go to wallet (https://beta.dlist.top/wallet)
2. Choose how much and method payment
3. Click buy

**Expected behavior**
Get site where i can pay using choosen payment method

**Screenshots**
![unknown](https://user-images.githubusercontent.com/68489269/126465205-45b84cc2-2d28-4148-8c82-375830589988.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera

**Comment by SushiBtw** [comment]
All the api routes are now fixed and up to date.
